// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Infomation.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Infomation_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Infomation_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Infomation_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Infomation_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Infomation_2eproto;
class Infomation;
struct InfomationDefaultTypeInternal;
extern InfomationDefaultTypeInternal _Infomation_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Infomation* Arena::CreateMaybeMessage<::Infomation>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum RequestCode : int {
  Login = 0,
  Register = 1,
  RequestCode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  RequestCode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool RequestCode_IsValid(int value);
constexpr RequestCode RequestCode_MIN = Login;
constexpr RequestCode RequestCode_MAX = Register;
constexpr int RequestCode_ARRAYSIZE = RequestCode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* RequestCode_descriptor();
template<typename T>
inline const std::string& RequestCode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, RequestCode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function RequestCode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    RequestCode_descriptor(), enum_t_value);
}
inline bool RequestCode_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, RequestCode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<RequestCode>(
    RequestCode_descriptor(), name, value);
}
enum ResponseCode : int {
  LoginOK = 0,
  RegisterOK = 1,
  ResponseCode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ResponseCode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ResponseCode_IsValid(int value);
constexpr ResponseCode ResponseCode_MIN = LoginOK;
constexpr ResponseCode ResponseCode_MAX = RegisterOK;
constexpr int ResponseCode_ARRAYSIZE = ResponseCode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ResponseCode_descriptor();
template<typename T>
inline const std::string& ResponseCode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ResponseCode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ResponseCode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ResponseCode_descriptor(), enum_t_value);
}
inline bool ResponseCode_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ResponseCode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ResponseCode>(
    ResponseCode_descriptor(), name, value);
}
// ===================================================================

class Infomation final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Infomation) */ {
 public:
  inline Infomation() : Infomation(nullptr) {}
  ~Infomation() override;
  explicit PROTOBUF_CONSTEXPR Infomation(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Infomation(const Infomation& from);
  Infomation(Infomation&& from) noexcept
    : Infomation() {
    *this = ::std::move(from);
  }

  inline Infomation& operator=(const Infomation& from) {
    CopyFrom(from);
    return *this;
  }
  inline Infomation& operator=(Infomation&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Infomation& default_instance() {
    return *internal_default_instance();
  }
  static inline const Infomation* internal_default_instance() {
    return reinterpret_cast<const Infomation*>(
               &_Infomation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Infomation& a, Infomation& b) {
    a.Swap(&b);
  }
  inline void Swap(Infomation* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Infomation* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Infomation* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Infomation>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Infomation& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Infomation& from) {
    Infomation::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Infomation* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Infomation";
  }
  protected:
  explicit Infomation(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserNameFieldNumber = 1,
    kData1FieldNumber = 2,
    kData2FieldNumber = 3,
    kData3FieldNumber = 4,
    kReqcodeFieldNumber = 5,
    kRescodeFieldNumber = 6,
  };
  // string userName = 1;
  void clear_username();
  const std::string& username() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_username(ArgT0&& arg0, ArgT... args);
  std::string* mutable_username();
  PROTOBUF_NODISCARD std::string* release_username();
  void set_allocated_username(std::string* username);
  private:
  const std::string& _internal_username() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_username(const std::string& value);
  std::string* _internal_mutable_username();
  public:

  // string data1 = 2;
  void clear_data1();
  const std::string& data1() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data1(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data1();
  PROTOBUF_NODISCARD std::string* release_data1();
  void set_allocated_data1(std::string* data1);
  private:
  const std::string& _internal_data1() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data1(const std::string& value);
  std::string* _internal_mutable_data1();
  public:

  // string data2 = 3;
  void clear_data2();
  const std::string& data2() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data2(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data2();
  PROTOBUF_NODISCARD std::string* release_data2();
  void set_allocated_data2(std::string* data2);
  private:
  const std::string& _internal_data2() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data2(const std::string& value);
  std::string* _internal_mutable_data2();
  public:

  // string data3 = 4;
  void clear_data3();
  const std::string& data3() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data3(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data3();
  PROTOBUF_NODISCARD std::string* release_data3();
  void set_allocated_data3(std::string* data3);
  private:
  const std::string& _internal_data3() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data3(const std::string& value);
  std::string* _internal_mutable_data3();
  public:

  // .RequestCode reqcode = 5;
  void clear_reqcode();
  ::RequestCode reqcode() const;
  void set_reqcode(::RequestCode value);
  private:
  ::RequestCode _internal_reqcode() const;
  void _internal_set_reqcode(::RequestCode value);
  public:

  // .ResponseCode rescode = 6;
  void clear_rescode();
  ::ResponseCode rescode() const;
  void set_rescode(::ResponseCode value);
  private:
  ::ResponseCode _internal_rescode() const;
  void _internal_set_rescode(::ResponseCode value);
  public:

  // @@protoc_insertion_point(class_scope:Infomation)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr username_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data1_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data2_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data3_;
    int reqcode_;
    int rescode_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Infomation_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Infomation

// string userName = 1;
inline void Infomation::clear_username() {
  _impl_.username_.ClearToEmpty();
}
inline const std::string& Infomation::username() const {
  // @@protoc_insertion_point(field_get:Infomation.userName)
  return _internal_username();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Infomation::set_username(ArgT0&& arg0, ArgT... args) {
 
 _impl_.username_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Infomation.userName)
}
inline std::string* Infomation::mutable_username() {
  std::string* _s = _internal_mutable_username();
  // @@protoc_insertion_point(field_mutable:Infomation.userName)
  return _s;
}
inline const std::string& Infomation::_internal_username() const {
  return _impl_.username_.Get();
}
inline void Infomation::_internal_set_username(const std::string& value) {
  
  _impl_.username_.Set(value, GetArenaForAllocation());
}
inline std::string* Infomation::_internal_mutable_username() {
  
  return _impl_.username_.Mutable(GetArenaForAllocation());
}
inline std::string* Infomation::release_username() {
  // @@protoc_insertion_point(field_release:Infomation.userName)
  return _impl_.username_.Release();
}
inline void Infomation::set_allocated_username(std::string* username) {
  if (username != nullptr) {
    
  } else {
    
  }
  _impl_.username_.SetAllocated(username, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.username_.IsDefault()) {
    _impl_.username_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Infomation.userName)
}

// string data1 = 2;
inline void Infomation::clear_data1() {
  _impl_.data1_.ClearToEmpty();
}
inline const std::string& Infomation::data1() const {
  // @@protoc_insertion_point(field_get:Infomation.data1)
  return _internal_data1();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Infomation::set_data1(ArgT0&& arg0, ArgT... args) {
 
 _impl_.data1_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Infomation.data1)
}
inline std::string* Infomation::mutable_data1() {
  std::string* _s = _internal_mutable_data1();
  // @@protoc_insertion_point(field_mutable:Infomation.data1)
  return _s;
}
inline const std::string& Infomation::_internal_data1() const {
  return _impl_.data1_.Get();
}
inline void Infomation::_internal_set_data1(const std::string& value) {
  
  _impl_.data1_.Set(value, GetArenaForAllocation());
}
inline std::string* Infomation::_internal_mutable_data1() {
  
  return _impl_.data1_.Mutable(GetArenaForAllocation());
}
inline std::string* Infomation::release_data1() {
  // @@protoc_insertion_point(field_release:Infomation.data1)
  return _impl_.data1_.Release();
}
inline void Infomation::set_allocated_data1(std::string* data1) {
  if (data1 != nullptr) {
    
  } else {
    
  }
  _impl_.data1_.SetAllocated(data1, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.data1_.IsDefault()) {
    _impl_.data1_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Infomation.data1)
}

// string data2 = 3;
inline void Infomation::clear_data2() {
  _impl_.data2_.ClearToEmpty();
}
inline const std::string& Infomation::data2() const {
  // @@protoc_insertion_point(field_get:Infomation.data2)
  return _internal_data2();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Infomation::set_data2(ArgT0&& arg0, ArgT... args) {
 
 _impl_.data2_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Infomation.data2)
}
inline std::string* Infomation::mutable_data2() {
  std::string* _s = _internal_mutable_data2();
  // @@protoc_insertion_point(field_mutable:Infomation.data2)
  return _s;
}
inline const std::string& Infomation::_internal_data2() const {
  return _impl_.data2_.Get();
}
inline void Infomation::_internal_set_data2(const std::string& value) {
  
  _impl_.data2_.Set(value, GetArenaForAllocation());
}
inline std::string* Infomation::_internal_mutable_data2() {
  
  return _impl_.data2_.Mutable(GetArenaForAllocation());
}
inline std::string* Infomation::release_data2() {
  // @@protoc_insertion_point(field_release:Infomation.data2)
  return _impl_.data2_.Release();
}
inline void Infomation::set_allocated_data2(std::string* data2) {
  if (data2 != nullptr) {
    
  } else {
    
  }
  _impl_.data2_.SetAllocated(data2, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.data2_.IsDefault()) {
    _impl_.data2_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Infomation.data2)
}

// string data3 = 4;
inline void Infomation::clear_data3() {
  _impl_.data3_.ClearToEmpty();
}
inline const std::string& Infomation::data3() const {
  // @@protoc_insertion_point(field_get:Infomation.data3)
  return _internal_data3();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Infomation::set_data3(ArgT0&& arg0, ArgT... args) {
 
 _impl_.data3_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Infomation.data3)
}
inline std::string* Infomation::mutable_data3() {
  std::string* _s = _internal_mutable_data3();
  // @@protoc_insertion_point(field_mutable:Infomation.data3)
  return _s;
}
inline const std::string& Infomation::_internal_data3() const {
  return _impl_.data3_.Get();
}
inline void Infomation::_internal_set_data3(const std::string& value) {
  
  _impl_.data3_.Set(value, GetArenaForAllocation());
}
inline std::string* Infomation::_internal_mutable_data3() {
  
  return _impl_.data3_.Mutable(GetArenaForAllocation());
}
inline std::string* Infomation::release_data3() {
  // @@protoc_insertion_point(field_release:Infomation.data3)
  return _impl_.data3_.Release();
}
inline void Infomation::set_allocated_data3(std::string* data3) {
  if (data3 != nullptr) {
    
  } else {
    
  }
  _impl_.data3_.SetAllocated(data3, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.data3_.IsDefault()) {
    _impl_.data3_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Infomation.data3)
}

// .RequestCode reqcode = 5;
inline void Infomation::clear_reqcode() {
  _impl_.reqcode_ = 0;
}
inline ::RequestCode Infomation::_internal_reqcode() const {
  return static_cast< ::RequestCode >(_impl_.reqcode_);
}
inline ::RequestCode Infomation::reqcode() const {
  // @@protoc_insertion_point(field_get:Infomation.reqcode)
  return _internal_reqcode();
}
inline void Infomation::_internal_set_reqcode(::RequestCode value) {
  
  _impl_.reqcode_ = value;
}
inline void Infomation::set_reqcode(::RequestCode value) {
  _internal_set_reqcode(value);
  // @@protoc_insertion_point(field_set:Infomation.reqcode)
}

// .ResponseCode rescode = 6;
inline void Infomation::clear_rescode() {
  _impl_.rescode_ = 0;
}
inline ::ResponseCode Infomation::_internal_rescode() const {
  return static_cast< ::ResponseCode >(_impl_.rescode_);
}
inline ::ResponseCode Infomation::rescode() const {
  // @@protoc_insertion_point(field_get:Infomation.rescode)
  return _internal_rescode();
}
inline void Infomation::_internal_set_rescode(::ResponseCode value) {
  
  _impl_.rescode_ = value;
}
inline void Infomation::set_rescode(::ResponseCode value) {
  _internal_set_rescode(value);
  // @@protoc_insertion_point(field_set:Infomation.rescode)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::RequestCode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::RequestCode>() {
  return ::RequestCode_descriptor();
}
template <> struct is_proto_enum< ::ResponseCode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ResponseCode>() {
  return ::ResponseCode_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Infomation_2eproto
